#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

modelVersion: "2.0"
flavor: "ADP 2.0"
service:
    # name of the service:
    name: "Python Package Repository"
    # Design Country (set on the source products)
    design_countries:
        - SE
    # Country of Origin (Set on the derivative products)
    sw_compilation_country: SE
    # Release responsible
    release_responsible: BCSSIFB
    # Design responsible
    design_responsible: BCSSIFB
    # The documents is optional if all eridoc document revisions are set
    documents:
        # Read documents revisions from this file
        # Use munin-doc search and pri.py to generate this file.
        # Use full or relative path to product_structure.yaml
        import: ../../build/documents.yaml
    # Details of the APR product structure:
    top_product:
        # Note: all derivative_products are automatically added to APR product structure
        # APR Product Number
        number: APR 201 939
        # Designation
        designation: Python Package Repository
        # Description
        description: |-
            Python Python Package Repository, based on pypiserver provides hosting, distribution, and management of Python packages.
        # Alias designation, use the Helm Chart name
        alias:
            - eric-lcm-package-repository
        # Included documents and products
        includes:
            # PRI
            - eridoc: 109 21-APR 201 939-1
              step_strategy: highest revision letter
            # User Guide
            - eridoc: 1/1553-APR 201 939
              step_strategy: highest revision letter
            # Test Specification
            - eridoc: 1/152 41-APR 201 939
              step_strategy: highest revision letter
            # Test Report
            - eridoc: 1/152 83-APR 201 939-1
              step_strategy: highest revision letter
            # Risk Assessment doc
            - eridoc: 1/006 64-APR 201 939
              step_strategy: highest revision letter
            # Secure Coding doc
            #- eridoc: 1/0360-APR 201 939
            #  step_strategy: highest revision letter
            # Vulnerability Analysis Report
            - eridoc: 1/1597-APR 201 939
              step_strategy: highest revision letter
            # SUSE Licenses
            - prim: 1/FAL 115 3215
              rstate: R1A
            - prim: 3/FAL 115 3215
              rstate: R1A
            - prim: 5/FAL 115 3215
              rstate: R1A
            - prim: 7/FAL 115 3215
              rstate: R1A
    # Details of Source product structures
    src_products:
        # Source Code Product
        - label: "Python Package Repository Source"
          # Designation
          designation: Python Package Repository Source
          # Description
          description: >
              Python Python Package Repository, based on pypiserver provides hosting, distribution, and management of Python packages.
          # The product number
          number: CAV 101 1051
    # Details of zero or more derivative product structures, use [] for zero
    derivative_products:
        # Label describing the product, must be uniq per list item
        - label: "Python Package Repository Helm"
          # Designation
          designation: Python Package Repository Helm Chart
          # Description
          description: >
              The Helm Chart configuration file of Python Package Repository microservice to deploy on a Kubernetes cluster.
          # specific CXD product number
          number: CXD 101 723
          # Use the helm chart name as alias for the helm chart product
          alias:
              - eric-lcm-package-repository
          derivedFrom:
              munin: CAV 101 1051
        - label: "Python Package Repository PyPi IMAGE"
          # Designation
          designation: Python Package Repository PyPi IMAGE
          # Description
          description: >
              The container image of Python Package Repository.
          # specific CXU product number
          number: CXU 101 2163
          includes:
              # Common Base OS Image
              - munin: CXC 201 2032
                version: ##CBOS_VERSION##
                secondPartyProduct: "True"
              # Common Base OS Repository
              - munin: CXC 201 2031
                version: ##CBOS_VERSION##
                secondPartyProduct: "True"
              # Stdout-Redirect SW Library
              - munin: CXA 301 76
                version: ##STDOUT_REDIRECT_VERSION##
                secondPartyProduct: "True"
          uses_foss:
              # Create a dependencies file just for this image
              - dependencies_file: ../fossa/dependencies.pypiserver.yaml
              - foss_usage: ../fossa/foss-usage.yaml
          uses_encryption:
              - import: ../fossa/encryptions.yaml
          derivedFrom:
              munin: CAV 101 1051