#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.ingress.enabled }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ include "eric-lcm-package-repository-py.name" . }}
  labels: {{ include "eric-lcm-package-repository-py.labels" . | nindent 4 }}
  annotations: {{- include "eric-lcm-package-repository-py.iccrHttpProxyAnnotations" . | nindent 4 }}
spec:
  virtualhost:
      fqdn: {{ .Values.ingress.hostname | quote }}
      {{- if .Values.ingress.tls.enabled }}
      tls:
        secretName: {{ .Values.ingress.tls.secretName | quote }}
      {{- end }}
  includes:
    - name: {{ include "eric-lcm-package-repository-py.name" . }}-routes
      namespace: {{ .Release.Namespace }}
{{- end -}}
