#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if eq (include "eric-lcm-package-repository-py.serviceMesh.enabled" .) "true" }}
{{- if .Values.serviceMesh.egress.ericlcmpackagerepositorypy.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "eric-lcm-package-repository-py.name" . }}-destinationrule-model-lcm
  labels: {{ include "eric-lcm-package-repository-py.labels" . | nindent 4 }}
  annotations: {{ include "eric-lcm-package-repository-py.annotations" . | nindent 4 }}
spec:
  host: {{ include "eric-lcm-package-repository-py.name" . }}
  {{- if eq (include "eric-lcm-package-repository-py.global-security-tls-enabled" .) "true" }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  {{- else }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  {{- end }}
{{- end }}
{{- end }}
