#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if .Values.brAgent.enabled -}}
{{- if .Values.global -}}
  {{- if .Values.global.security -}}
    {{- if .Values.global.security.policyBinding -}}
      {{- if .Values.global.security.policyBinding.create -}}
      
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-lcm-package-repository-py.name" . }}-bragent-security-policy
  labels: {{- include "eric-lcm-package-repository-py.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-lcm-package-repository-py.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eric-lcm-package-repository-py.securityPolicy.reference" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-lcm-package-repository-py.name" . }}-bragent
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}