#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.brAgent.enabled -}}
{{- if .Values.global -}}
  {{- if .Values.global.securityPolicy -}}
    {{- if ne .Values.global.securityPolicy.rolekind "" -}}
      {{- $rolekind := .Values.global.securityPolicy.rolekind }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-lcm-package-repository-py.name" . }}-bragent-{{ lower (trunc 1 $rolekind) }}-{{ .Values.securityPolicy.bragent.rolename  }}-sp
  labels: {{ include "eric-lcm-package-repository-py.labels" . | nindent 4 }}
  annotations: {{ include "eric-lcm-package-repository-py.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "eric-lcm-package-repository-py.securityPolicy.rolekind" . }}
  name: {{ .Values.securityPolicy.bragent.rolename }}
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-lcm-package-repository-py.name" . }}-bragent
    namespace: '{{ .Release.Namespace }}'
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}
