#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if .Values.brAgent.enabled -}}
{{ $global := fromYaml ( include "eric-lcm-package-repository-py.global" . ) -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "eric-lcm-package-repository-py.fullname" . }}-bragent"
  labels:
    {{- include "eric-lcm-package-repository-py.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-lcm-package-repository-py.annotations" . | nindent 4 }}
spec:
{{- if $global.internalIPFamily }}
  ipFamilies: [{{ $global.internalIPFamily | quote }}]
{{- end }}
  # default service type
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.brAgent.restPort }}
      targetPort: {{ .Values.brAgent.restPort }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- end }}