#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ $global := fromYaml ( include "eric-lcm-package-repository-py.global" . ) -}}
{{- if and .Values.brAgent.enabled $global.security.tls.enabled }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-lcm-package-repository-py.name" .}}-bro-client-cert
  labels:
    {{- include "eric-lcm-package-repository-py.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-lcm-package-repository-py.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-lcm-package-repository-py.brAgent.broCliCertSecretName" .}}
    certificateName: clicert.pem
    privateKeyName: cliprivkey.pem
  certificate:
    subject:
      cn: {{ template "eric-lcm-package-repository-py.name" .}}
    issuer:
      reference: {{ $global.adpBR.broServiceName }}-ca
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}
